# Generated by Django 5.2.3 on 2025-07-30 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('store_name', models.CharField(max_length=100)),
                ('store_type', models.CharField(choices=[('men', 'men'), ('food', 'food'), ('women', 'women'), ('kids', 'kids'), ('accessories', 'accessories'), ('shoes', 'shoes'), ('bags', 'bags'), ('jewelry', 'jewelry'), ('home', 'home'), ('beauty', 'beauty')], default='food')),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('phone_number', models.IntegerField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='store_images/')),
            ],
        ),
    ]
