# Generated by Django 5.2.3 on 2025-07-30 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createstorevendorform', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstore',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
