# Generated by Django 5.2.3 on 2025-08-03 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_sendemail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sendemail',
            options={},
        ),
        migrations.RenameField(
            model_name='sendemail',
            old_name='phon',
            new_name='phone',
        ),
    ]
