# Generated by Django 5.2.3 on 2025-08-03 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_sendemail_options_rename_phon_sendemail_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sendemail',
        ),
    ]
