# Generated by Django 5.2.3 on 2025-07-31 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='categoress',
            field=models.CharField(max_length=100),
        ),
    ]
