# Generated by Django 5.2.3 on 2025-07-31 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_category_categoress'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='descreption',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='categoress',
            field=models.CharField(choices=[('men', 'men'), ('food', 'food'), ('women', 'women'), ('kids', 'kids'), ('accessories', 'accessories'), ('shoes', 'shoes'), ('bags', 'bags'), ('jewelry', 'jewelry'), ('home', 'home'), ('beauty', 'beauty')], default='men', max_length=100),
        ),
    ]
