# Generated by Django 5.2.3 on 2025-08-01 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_category_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='VendorCategories', to='core.vendor'),
        ),
    ]
